#pragma once
#include "common.h"

namespace ntt {

enum ExpressionType
{
	EXPRESSION_TYPE_UNKNOWN,
	EXPRESSION_TYPE_EPSILON,
	EXPRESSION_TYPE_LITERAL,
	EXPRESSION_TYPE_IDENTIFIER,
	EXPRESSION_TYPE_FUNCTION_CALL,
	EXPRESSION_TYPE_FUNCTION,
	EXPRESSION_TYPE_PROGRAM,
	EXPRESSION_TYPE_ADD,
	EXPRESSION_TYPE_SUBTRACT,
	EXPRESSION_TYPE_MULTIPLY,
	EXPRESSION_TYPE_DIVIDE,
	EXPRESSION_TYPE_COMPARE_LESS,
	EXPRESSION_TYPE_COMPARE_GREATER,
	EXPRESSION_TYPE_COMPARE_EQUAL,
	EXPRESSION_TYPE_COMPARE_NOT_EQUAL,
	EXPRESSION_TYPE_COMPARE_LESS_EQUAL,
	EXPRESSION_TYPE_COMPARE_GREATER_EQUAL,
	EXPRESSION_TYPE_VARIABLE_DECLARATION,
	EXPRESSION_TYPE_RETURN,
	EXPRESSION_TYPE_BLOCK,
	EXPRESSION_TYPE_COUNT,
};

} // namespace ntt
